baseURL = "https://lemmebee.github.io/feki.dev/"
languageCode = "en-us"
title = "feki.dev"
theme = "nostyleplease"

[params]
  author = "Ehab ELFEKI"
  favicon = "favicon.svg"
  
  [params.theme_config]
    appearance = "dark" # valid options: light, dark, auto
    back_home_text = "← home"
    date_format = "2006-01-02"
    show_description = true
